spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  # xml 扫描路径
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

logging:
  path: ./logs
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.lucky: debug

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 600000 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
